version: "3.9"
services:
  backend:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32520:5050"
    depends_on:
      - "memcached"
    restart: always
    environment:
      - GO_PORT=5050
      - ROOT_PATH=/app
    volumes:
      - ./:/app
    networks:
      - go-network

  db:
    image: mysql:latest
    container_name: go-mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: rp
      MYSQL_ROOT_PASSWORD: 6i6Eo0v812
    ports:
      - '32522:3306'
    volumes:
      - ./storage/db/mysql:/var/lib/mysql
    networks:
      - go-network

  memcached:
    container_name: go-mcd
    image: memcached
    ports:
      - "32523:11211"
    networks:
      - go-network

networks:
  go-network:
    external: true
