version: '3.7'

services:
  mongo1:
    build: .
    hostname: mongo1
    ports:
      - "27017:27017"
    entrypoint: ["bash", "-c", " /scripts/init-replica-set.sh"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rust_drop
      - MONGO_INITDB_ROOT_PASSWORD=<H;wFO&:L:ym;9
    volumes:
      - ./mongo1-data:/data/db
      - ./init-replica-set.sh:/scripts/init-replica-set.sh
    networks:
      - go-rust-drop-network

  mongo2:
    build: .
    hostname: mongo2
    ports:
      - "27018:27018"
    command: --replSet rs0 --keyFile /etc/mongo/keyfile --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rust_drop
      - MONGO_INITDB_ROOT_PASSWORD=<H;wFO&:L:ym;9
    volumes:
      - ./mongo2-data:/data/db
    networks:
      - go-rust-drop-network

  mongo3:
    build: .
    hostname: mongo3
    ports:
      - "27019:27019"
    command: --replSet rs0 --keyFile /etc/mongo/keyfile --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rust_drop
      - MONGO_INITDB_ROOT_PASSWORD=<H;wFO&:L:ym;9
    volumes:
      - ./mongo3-data:/data/db
    networks:
      - go-rust-drop-network

networks:
  go-rust-drop-network:
    external: true

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
